In [4]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
#import pandas 
import pandas as pd

In [6]:
#check version:
pd.__version__

'3.0.3'

In [7]:
#pandas = DataFrames(work on rows and columns)
# 1. create DataFrame
df = pd.DataFrame([1,2,3] , columns=["col_name"])
print(df)

   col_name
0         1
1         2
2         3

In [8]:
print(type(df))

<class 'pandas.DataFrame'>

In [9]:
# create dataframe with multiple columns:-

data = { 
    'Name' : ["madhav" , "vanshika" , " lalita" , " rishab"],
    "age" : [ 10 , 16,19 , 20],
    "salary" : [ 90000 , 10000 , 15000 , 20000]
}
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  age  salary
0    madhav   10   90000
1  vanshika   16   10000
2    lalita   19   15000
3    rishab   20   20000
<class 'pandas.DataFrame'>

In [10]:
#2. basic understanding of dataframe
df.head(2) # top two  rows
df.tail(2) # last two rows
df.shape # gave the no. f rows and columns
df.columns # gave the name of all the columns
df.rename(columns={"salary" : "monthly_Salary"} , inplace = True)# rename any columns name
print(df)

       Name  age  monthly_Salary
0    madhav   10           90000
1  vanshika   16           10000
2    lalita   19           15000
3    rishab   20           20000

In [11]:
df.info() # gave the information of the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   age             4 non-null      int64
 2   monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [12]:
df.describe()

         age  monthly_Salary
count   4.00        4.000000
mean   16.25    33750.000000
std     4.50    37721.567659
min    10.00    10000.000000
25%    14.50    13750.000000
50%    17.50    17500.000000
75%    19.25    37500.000000
max    20.00    90000.000000

In [13]:
# save and load data frame csv
df.to_csv("test_data.csv" , index = False) # export data frame

In [14]:
# function for load dataframe

load_df = pd.read_csv("test_data.csv") #import dataframe
print(load_df)

       Name  age  monthly_Salary
0    madhav   10           90000
1  vanshika   16           10000
2    lalita   19           15000
3    rishab   20           20000

In [15]:
#4. rows and columns - selection
#select columns
# df[['name']] # single column
df[['Name', 'monthly_Salary']]

       Name  monthly_Salary
0    madhav           90000
1  vanshika           10000
2    lalita           15000
3    rishab           20000

In [16]:
#select rows
#loc = label based index
df.loc[df.Name =="vanshika"] # select row with index 1
df.loc[(df.Name=="madhav") & (df.monthly_Salary>=10000)]

     Name  age  monthly_Salary
0  madhav   10           90000

In [17]:
# iloc = index based selection
#loc = gave the 3 means 3 name but iloc gave 1 lesser.
df.iloc[1] 
df.iloc[0:2]
df.iloc[:3]
df.iloc[0:3:2] # start :stop: step
df.loc[0:2]

       Name  age  monthly_Salary
0    madhav   10           90000
1  vanshika   16           10000
2    lalita   19           15000

In [18]:
# how filters the dataframe
df["age"]>15 # if we want only boolean value use only one df
df[df["age"]>15] # if we want their name with inf.

       Name  age  monthly_Salary
1  vanshika   16           10000
2    lalita   19           15000
3    rishab   20           20000

In [19]:
#store the age in new variable
df_age_filter = df[df["age"]>15]
df_age_filter

       Name  age  monthly_Salary
1  vanshika   16           10000
2    lalita   19           15000
3    rishab   20           20000

In [20]:
#more than one condition for filter the data
df[(df["age"]>=18) & (df["monthly_Salary"]>=15000)]

      Name  age  monthly_Salary
2   lalita   19           15000
3   rishab   20           20000

In [21]:
df.where(df["age"] >=18)

      Name   age  monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   lalita  19.0         15000.0
3   rishab  20.0         20000.0

In [22]:
#add new column
df["team"] = ["ceo" , "hr" , "cto" , "da"]
df

       Name  age  monthly_Salary team
0    madhav   10           90000  ceo
1  vanshika   16           10000   hr
2    lalita   19           15000  cto
3    rishab   20           20000   da

In [23]:
# add the new column with new method
df["bonus"] = df["monthly_Salary"]*0.2
df

       Name  age  monthly_Salary team    bonus
0    madhav   10           90000  ceo  18000.0
1  vanshika   16           10000   hr   2000.0
2    lalita   19           15000  cto   3000.0
3    rishab   20           20000   da   4000.0

In [24]:
#add new row
df.loc[len(df)] = ["abc" , 21 , 21000 , "it" , 2000]
df

       Name  age  monthly_Salary team    bonus
0    madhav   10           90000  ceo  18000.0
1  vanshika   16           10000   hr   2000.0
2    lalita   19           15000  cto   3000.0
3    rishab   20           20000   da   4000.0
4       abc   21           21000   it   2000.0

In [25]:
len(df)

5

In [26]:
# update the value  of row - using  index name
df.loc[0, "monthly_Salary"] = 80000
df

       Name  age  monthly_Salary team    bonus
0    madhav   10           80000  ceo  18000.0
1  vanshika   16           10000   hr   2000.0
2    lalita   19           15000  cto   3000.0
3    rishab   20           20000   da   4000.0
4       abc   21           21000   it   2000.0

In [27]:
#update value = using the column value
df.loc[df.Name == "madhav" , "monthly_Salary"] = 90000
df

       Name  age  monthly_Salary team    bonus
0    madhav   10           90000  ceo  18000.0
1  vanshika   16           10000   hr   2000.0
2    lalita   19           15000  cto   3000.0
3    rishab   20           20000   da   4000.0
4       abc   21           21000   it   2000.0

In [28]:
# delete value - row and column values
df = df.drop(df[df.Name == "abc"].index) # drop row , axis = 0
df
df.drop(1, axis = 0)

      Name  age  monthly_Salary team    bonus
0   madhav   10           90000  ceo  18000.0
2   lalita   19           15000  cto   3000.0
3   rishab   20           20000   da   4000.0

In [29]:
df.drop("bonus" , axis = 1)

       Name  age  monthly_Salary team
0    madhav   10           90000  ceo
1  vanshika   16           10000   hr
2    lalita   19           15000  cto
3    rishab   20           20000   da

In [30]:
#sort the value
df.sort_values("monthly_Salary" )

       Name  age  monthly_Salary team    bonus
1  vanshika   16           10000   hr   2000.0
2    lalita   19           15000  cto   3000.0
3    rishab   20           20000   da   4000.0
0    madhav   10           90000  ceo  18000.0

In [ ]:
df.sort_values("monthly_Salary" , ascending = False) # descending order.

       Name  age  monthly_Salary team    bonus
0    madhav   10           90000  ceo  18000.0
3    rishab   20           20000   da   4000.0
2    lalita   19           15000  cto   3000.0
1  vanshika   16           10000   hr   2000.0

In [33]:
# working with date value 
df["DOJ"] = ["2024-01-20" , "2024-02-19" , "2026-04-20" , "2026-07-30" ]
df

       Name  age  monthly_Salary team    bonus         DOJ
0    madhav   10           90000  ceo  18000.0  2024-01-20
1  vanshika   16           10000   hr   2000.0  2024-02-19
2    lalita   19           15000  cto   3000.0  2026-04-20
3    rishab   20           20000   da   4000.0  2026-07-30

In [35]:
df["DOJ"].dtype

In [37]:
df["DOJ"] = pd.to_datetime(df["DOJ"])
df["DOJ"].dtype

dtype('<M8[us]')

In [38]:
df1 = df
df1

       Name  age  monthly_Salary team    bonus        DOJ
0    madhav   10           90000  ceo  18000.0 2024-01-20
1  vanshika   16           10000   hr   2000.0 2024-02-19
2    lalita   19           15000  cto   3000.0 2026-04-20
3    rishab   20           20000   da   4000.0 2026-07-30

In [40]:
df1["DOJ2"] = ["01-01-2025" , "10-02-2026" , "20-04-2026" , "19-07-2026"]
df1

       Name  age  monthly_Salary team    bonus        DOJ        DOJ2
0    madhav   10           90000  ceo  18000.0 2024-01-20  01-01-2025
1  vanshika   16           10000   hr   2000.0 2024-02-19  10-02-2026
2    lalita   19           15000  cto   3000.0 2026-04-20  20-04-2026
3    rishab   20           20000   da   4000.0 2026-07-30  19-07-2026

In [41]:
df1["DOJ2"].dtype

In [43]:
df1["DOJ2"] = pd.to_datetime(df1["DOJ2"] , format = "%d-%m-%Y")

In [44]:
df1["DOJ2"].dtype

dtype('<M8[us]')

In [45]:
df

       Name  age  monthly_Salary team    bonus        DOJ       DOJ2
0    madhav   10           90000  ceo  18000.0 2024-01-20 2025-01-01
1  vanshika   16           10000   hr   2000.0 2024-02-19 2026-02-10
2    lalita   19           15000  cto   3000.0 2026-04-20 2026-04-20
3    rishab   20           20000   da   4000.0 2026-07-30 2026-07-19

In [ ]:
df = df.drop("DOJ2" , axis = 1)df

       Name  age  monthly_Salary team    bonus        DOJ
0    madhav   10           90000  ceo  18000.0 2024-01-20
1  vanshika   16           10000   hr   2000.0 2024-02-19
2    lalita   19           15000  cto   3000.0 2026-04-20
3    rishab   20           20000   da   4000.0 2026-07-30

In [49]:
# extract year , month , date , day
df["DOJ"].dt.year
df["DOJ"].dt.month
df["DOJ"].dt.day
df["DOJ"].dt.day_name()

0    Saturday
1      Monday
2      Monday
3    Thursday
Name: DOJ, dtype: str

In [50]:
df["month"] = df["DOJ"].dt.month
df

       Name  age  monthly_Salary team    bonus        DOJ  month
0    madhav   10           90000  ceo  18000.0 2024-01-20      1
1  vanshika   16           10000   hr   2000.0 2024-02-19      2
2    lalita   19           15000  cto   3000.0 2026-04-20      4
3    rishab   20           20000   da   4000.0 2026-07-30      7

In [ ]:
df["DOJ"] + pd.Timedelta(days = 90) # add no. of dates and also subtract

0   2024-04-19
1   2024-05-19
2   2026-07-19
3   2026-10-28
Name: DOJ, dtype: datetime64[us]

In [52]:
# handling the missing values
df.isnull()

    Name    age  monthly_Salary   team  bonus    DOJ  month
0  False  False           False  False  False  False  False
1  False  False           False  False  False  False  False
2  False  False           False  False  False  False  False
3  False  False           False  False  False  False  False

In [55]:
import numpy as np
df.loc[df.Name == "vanshika" , "monthly_Salary"] = np.nan
df

       Name  age  monthly_Salary team    bonus        DOJ  month
0    madhav   10         90000.0  ceo  18000.0 2024-01-20      1
1  vanshika   16             NaN   hr   2000.0 2024-02-19      2
2    lalita   19         15000.0  cto   3000.0 2026-04-20      4
3    rishab   20         20000.0   da   4000.0 2026-07-30      7

In [56]:
df.isnull().sum()

Name              0
age               0
monthly_Salary    1
team              0
bonus             0
DOJ               0
month             0
dtype: int64

In [57]:
df.fillna(0)

       Name  age  monthly_Salary team    bonus        DOJ  month
0    madhav   10         90000.0  ceo  18000.0 2024-01-20      1
1  vanshika   16             0.0   hr   2000.0 2024-02-19      2
2    lalita   19         15000.0  cto   3000.0 2026-04-20      4
3    rishab   20         20000.0   da   4000.0 2026-07-30      7

In [ ]:
#aggregation and group by
df["month"].value_counts() # freq. of value

month
1    1
2    1
4    1
7    1
Name: count, dtype: int64

In [61]:
df[df["month"]==1].value_counts() #

Name    age  monthly_Salary  team  bonus    DOJ         month
madhav  10   90000.0         ceo   18000.0  2024-01-20  1        1
Name: count, dtype: int64

In [67]:
df.groupby("month")["monthly_Salary"].sum()
df.groupby("month")["monthly_Salary"].mean()

month
1    90000.0
2        NaN
4    15000.0
7    20000.0
Name: monthly_Salary, dtype: float64

In [69]:
df.groupby("month").agg({"monthly_Salary" :"mean" , "Name" : "count"})

       monthly_Salary  Name
month
1             90000.0     1
2                 NaN     1
4             15000.0     1
7             20000.0     1

In [71]:
#concatenate and merge dataframes (joins)
df1 = pd.DataFrame({"ID" : [1,2,3] , "Name" : ['a' ,'b', 'c']})
df1

   ID Name
0   1    a
1   2    b
2   3    c

In [72]:
df2 = pd.DataFrame({"ID" :[1,2,4,3] , "score" : [ 33,44,5,5]})
df2

   ID  score
0   1     33
1   2     44
2   4      5
3   3      5

In [73]:
pd.concat([df1 , df2] , axis = 0 ) #vertical / row level / top

   ID Name  score
0   1    a    NaN
1   2    b    NaN
2   3    c    NaN
0   1  NaN   33.0
1   2  NaN   44.0
2   4  NaN    5.0
3   3  NaN    5.0

In [ ]:
pd.concat([df1 , df2] , axis = 1) 3 horizontal level

    ID Name  ID  score
0  1.0    a   1     33
1  2.0    b   2     44
2  3.0    c   4      5
3  NaN  NaN   3      5

In [79]:
# merge = join
pd.merge(df1 , df2 , how = "right" , on = "ID")

   ID Name  score
0   1    a     33
1   2    b     44
2   4  NaN      5
3   3    c      5

In [80]:
pd.merge(df1 , df2 , how = "inner" , left_on = "ID" , right_on = "ID")

   ID Name  score
0   1    a     33
1   2    b     44
2   3    c      5

In [82]:
# use of ai and chatgpt in pandas 
df

       Name  age  monthly_Salary team    bonus        DOJ  month
0    madhav   10         90000.0  ceo  18000.0 2024-01-20      1
1  vanshika   16             NaN   hr   2000.0 2024-02-19      2
2    lalita   19         15000.0  cto   3000.0 2026-04-20      4
3    rishab   20         20000.0   da   4000.0 2026-07-30      7

In [83]:
filtered_df = df[(df["monthly_Salary"] > 15000) & (df["age"] > 18)]

# 3. View the result
print(filtered_df)

      Name  age  monthly_Salary team   bonus        DOJ  month
3   rishab   20         20000.0   da  4000.0 2026-07-30      7

In [ ]:
# Clean and readable string-based filtering
filtered_df = df.query("monthly_Salary > 15000 and age > 18")print(filtered_df)

      Name  age  monthly_Salary team   bonus        DOJ  month
3   rishab   20         20000.0   da  4000.0 2026-07-30      7

In [88]:
import numpy as np
import pandas as pd

# Complete retail sales practice dataset
data = {
    "Region": [
        "North",
        "North",
        "South",
        "South",
        "East",
        "East",
        "West",
        "West",
        "North",
        "South",
    ],
    "Manager": [
        "Alice",
        "Alice",
        "Bob",
        "Bob",
        "Charlie",
        "Charlie",
        "David",
        "David",
        "Alice",
        "Bob",
    ],
    "Product": [
        "Laptop",
        "Phone",
        "Laptop",
        "Phone",
        "Laptop",
        "Phone",
        "Laptop",
        "Phone",
        "Laptop",
        "Phone",
    ],
    "Sales": [1200, 800, 1500, np.nan, 900, 600, 1100, 750, 1300, 700],
    "Quantity": [3, 5, 4, 1, 2, 4, 3, 5, 4, 3],
}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

--- Original DataFrame ---
  Region  Manager Product   Sales  Quantity
0  North    Alice  Laptop  1200.0         3
1  North    Alice   Phone   800.0         5
2  South      Bob  Laptop  1500.0         4
3  South      Bob   Phone     NaN         1
4   East  Charlie  Laptop   900.0         2
5   East  Charlie   Phone   600.0         4
6   West    David  Laptop  1100.0         3
7   West    David   Phone   750.0         5
8  North    Alice  Laptop  1300.0         4
9  South      Bob   Phone   700.0         3